# Generated by Strapi webhook
# Entrypoint: fxa_avatar_menu
# Generated at: 2025-07-25T17:25:24.030Z

5882386c6d801776-fxa_avatar_menu-shared-logoAltText-8dfae10c = Firefox logoo
5882386c6d801776-fxa_avatar_menu-shared-emailLogoAltText-96e4284e = Firefox logo
5882386c6d801776-fxa_avatar_menu-shared-emailFromName-763f7f1a = Firefox
5882386c6d801776-fxa_avatar_menu-EmailFirstPage-headline-33e9f42d = Continue to your Mozilla account
5882386c6d801776-fxa_avatar_menu-EmailFirstPage-description-4ac18cac = Sync your passwords, tabs, and bookmarks everywhere you use Firefox.
5882386c6d801776-fxa_avatar_menu-EmailFirstPage-primaryButtonText-e0c4332e = Get Started
5882386c6d801776-fxa_avatar_menu-SignupSetPasswordPage-headline-7e0aff4a = Set your password
5882386c6d801776-fxa_avatar_menu-SignupSetPasswordPage-description-9383a42f = Create a strong and secure password to encrypt your data.
5882386c6d801776-fxa_avatar_menu-SignupSetPasswordPage-primaryButtonText-af214972 = Set Password
5882386c6d801776-fxa_avatar_menu-SignupConfirmCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-fxa_avatar_menu-SignupConfirmCodePage-description-1e791281 = One last step, verify your account email address.
5882386c6d801776-fxa_avatar_menu-SignupConfirmCodePage-primaryButtonText-6b862186 = Confirm Email
5882386c6d801776-fxa_avatar_menu-SignupConfirmedSyncPage-headline-d8e87c09 = Sync
5882386c6d801776-fxa_avatar_menu-SignupConfirmedSyncPage-description-80ddaf0e = Your passwords, addresses, bookmarks, history, and more can sync everywhere you use Firefox...
5882386c6d801776-fxa_avatar_menu-SignupConfirmedSyncPage-primaryButtonText-49477717 = The next thing
5882386c6d801776-fxa_avatar_menu-SigninPage-headline-e8d28194 = Enter your password
5882386c6d801776-fxa_avatar_menu-SigninPage-description-673ee3c7 = to log into Firefox and start syncing.
5882386c6d801776-fxa_avatar_menu-SigninPage-primaryButtonText-b6d4223e = Sign in
5882386c6d801776-fxa_avatar_menu-SigninTokenCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-fxa_avatar_menu-SigninTokenCodePage-description-1e791281 = One last step, verify your account email address.
5882386c6d801776-fxa_avatar_menu-SigninTokenCodePage-primaryButtonText-a0bfb8e5 = Continue
5882386c6d801776-fxa_avatar_menu-SigninUnblockCodePage-headline-32aa265b = Autorize this sign in
5882386c6d801776-fxa_avatar_menu-SigninUnblockCodePage-description-a7ba1d71 = We want to make sure it is you. Verify your email addres.
5882386c6d801776-fxa_avatar_menu-SigninUnblockCodePage-primaryButtonText-7f83df9c = Authorize
5882386c6d801776-fxa_avatar_menu-NewDeviceLoginEmail-headline-a0a749e1 = New sign-in to Firefox
5882386c6d801776-fxa_avatar_menu-NewDeviceLoginEmail-description-361824c1 = You have signed into Firefox
5882386c6d801776-fxa_avatar_menu-NewDeviceLoginEmail-subject-a0a749e1 = New sign-in to Firefox
5882386c6d801776-fxa_avatar_menu-VerifyLoginCodeEmail-headline-fe389eef = Enter the verification code in Firefox
5882386c6d801776-fxa_avatar_menu-VerifyLoginCodeEmail-description-fe389eef = Enter the verification code in Firefox
5882386c6d801776-fxa_avatar_menu-VerifyLoginCodeEmail-subject-450ba359 = Approve sign-in to Firefox
5882386c6d801776-fxa_avatar_menu-VerifyShortCodeEmail-headline-e2bbf688 = Confirm your email address to begin syncing your browser.
5882386c6d801776-fxa_avatar_menu-VerifyShortCodeEmail-description-e2bbf688 = Confirm your email address to begin syncing your browser.
5882386c6d801776-fxa_avatar_menu-VerifyShortCodeEmail-subject-ef1fb997 = Confirm your account