# Generated by Strapi webhook
# Entrypoint: all-entries
# Generated at: 2025-08-01T18:06:14.572Z

# Generated by Strapi webhook
# Generated at: 2025-08-01T18:06:14.430Z
# Total entries: 3
# FTL entries: 93


# 5882386c6d801776 - firefox
# Entry ID: 71
# Name: Desktop Sync222221
# Created: 2025-06-27T19:16:17.077Z
# Updated: 2025-07-25T18:21:55.773Z

5882386c6d801776-firefox-shared-logoAltText-0247f558 = Firefox logo123
5882386c6d801776-firefox-shared-emailLogoAltText-96e4284e = Firefox logo
5882386c6d801776-firefox-shared-emailFromName-502f1bd9 = Mozilla
5882386c6d801776-firefox-EmailFirstPage-headline-33e9f42d = Continue to your Mozilla account
5882386c6d801776-firefox-EmailFirstPage-description-4ac18cac = Sync your passwords, tabs, and bookmarks everywhere you use Firefox.
5882386c6d801776-firefox-EmailFirstPage-primaryButtonText-a20eb81e = Sign up or sign in
5882386c6d801776-firefox-SignupSetPasswordPage-headline-72786b8a = Create a password
5882386c6d801776-firefox-SignupSetPasswordPage-description-201c6fe1 = Sync your passwords, payment methods, bookmarks, and more everywhere you use Firefox.
5882386c6d801776-firefox-SignupSetPasswordPage-primaryButtonText-42369faa = Create account
5882386c6d801776-firefox-SignupConfirmCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-firefox-SignupConfirmCodePage-description-daaed757 = Just one quick step. Enter the code from your email to activate your Mozilla account.
5882386c6d801776-firefox-SignupConfirmCodePage-primaryButtonText-e4029ca4 = Start syncing
5882386c6d801776-firefox-SignupConfirmedSyncPage-headline-3ed2d228 = Sync is turned on
5882386c6d801776-firefox-SignupConfirmedSyncPage-description-2115ee89 = Your passwords, payment methods, addresses, bookmarks, history, and more can sync everywhere you use Firefox.
5882386c6d801776-firefox-SignupConfirmedSyncPage-primaryButtonText-598649e6 = Add another device
5882386c6d801776-firefox-SigninPage-headline-e8d28194 = Enter your password
5882386c6d801776-firefox-SigninPage-description-8286e168 = for your Mozilla account
5882386c6d801776-firefox-SigninPage-primaryButtonText-b6d4223e = Sign in
5882386c6d801776-firefox-SigninTokenCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-firefox-SigninTokenCodePage-description-8286e168 = for your Mozilla account
5882386c6d801776-firefox-SigninTokenCodePage-primaryButtonText-e4029ca4 = Start syncing
5882386c6d801776-firefox-SigninUnblockCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-firefox-SigninUnblockCodePage-description-8286e168 = for your Mozilla account
5882386c6d801776-firefox-SigninUnblockCodePage-primaryButtonText-a0bfb8e5 = Continue
5882386c6d801776-firefox-VerifyShortCodeEmail-headline-f8578b7c = Use the included code to confirm your Mozilla account.
5882386c6d801776-firefox-VerifyShortCodeEmail-description-ef1fb997 = Confirm your account
5882386c6d801776-firefox-VerifyShortCodeEmail-subject-ef1fb997 = Confirm your account

# 5882386c6d801776 - fxa_avatar_menu
# Entry ID: 83
# Name: Desktop Sync - fxa_avatar_menu
# Created: 2025-06-23T20:00:42.906Z
# Updated: 2025-07-31T18:31:33.262Z

5882386c6d801776-fxa_avatar_menu-shared-logoAltText-96e4284e = Firefox logo
5882386c6d801776-fxa_avatar_menu-shared-emailLogoAltText-96e4284e = Firefox logo
5882386c6d801776-fxa_avatar_menu-shared-emailFromName-763f7f1a = Firefox
5882386c6d801776-fxa_avatar_menu-EmailFirstPage-headline-33e9f42d = Continue to your Mozilla account
5882386c6d801776-fxa_avatar_menu-EmailFirstPage-description-4ac18cac = Sync your passwords, tabs, and bookmarks everywhere you use Firefox.
5882386c6d801776-fxa_avatar_menu-EmailFirstPage-primaryButtonText-e0c4332e = Get Started
5882386c6d801776-fxa_avatar_menu-SignupSetPasswordPage-headline-7e0aff4a = Set your password
5882386c6d801776-fxa_avatar_menu-SignupSetPasswordPage-description-9383a42f = Create a strong and secure password to encrypt your data.
5882386c6d801776-fxa_avatar_menu-SignupSetPasswordPage-primaryButtonText-af214972 = Set Password
5882386c6d801776-fxa_avatar_menu-SignupConfirmCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-fxa_avatar_menu-SignupConfirmCodePage-description-1e791281 = One last step, verify your account email address.
5882386c6d801776-fxa_avatar_menu-SignupConfirmCodePage-primaryButtonText-6b862186 = Confirm Email
5882386c6d801776-fxa_avatar_menu-SignupConfirmedSyncPage-headline-068241d3 = You are syncing Firefox
5882386c6d801776-fxa_avatar_menu-SignupConfirmedSyncPage-description-80ddaf0e = Your passwords, addresses, bookmarks, history, and more can sync everywhere you use Firefox...
5882386c6d801776-fxa_avatar_menu-SignupConfirmedSyncPage-primaryButtonText-49477717 = The next thing
5882386c6d801776-fxa_avatar_menu-SigninPage-headline-e8d28194 = Enter your password
5882386c6d801776-fxa_avatar_menu-SigninPage-description-673ee3c7 = to log into Firefox and start syncing.
5882386c6d801776-fxa_avatar_menu-SigninPage-primaryButtonText-b6d4223e = Sign in
5882386c6d801776-fxa_avatar_menu-SigninTokenCodePage-headline-d076f12b = Enter confirmation code
5882386c6d801776-fxa_avatar_menu-SigninTokenCodePage-description-1e791281 = One last step, verify your account email address.
5882386c6d801776-fxa_avatar_menu-SigninTokenCodePage-primaryButtonText-a0bfb8e5 = Continue
5882386c6d801776-fxa_avatar_menu-SigninUnblockCodePage-headline-32aa265b = Autorize this sign in
5882386c6d801776-fxa_avatar_menu-SigninUnblockCodePage-description-a7ba1d71 = We want to make sure it is you. Verify your email addres.
5882386c6d801776-fxa_avatar_menu-SigninUnblockCodePage-primaryButtonText-7f83df9c = Authorize
5882386c6d801776-fxa_avatar_menu-NewDeviceLoginEmail-headline-a0a749e1 = New sign-in to Firefox
5882386c6d801776-fxa_avatar_menu-NewDeviceLoginEmail-description-361824c1 = You have signed into Firefox
5882386c6d801776-fxa_avatar_menu-NewDeviceLoginEmail-subject-a0a749e1 = New sign-in to Firefox
5882386c6d801776-fxa_avatar_menu-VerifyLoginCodeEmail-headline-fe389eef = Enter the verification code in Firefox
5882386c6d801776-fxa_avatar_menu-VerifyLoginCodeEmail-description-fe389eef = Enter the verification code in Firefox
5882386c6d801776-fxa_avatar_menu-VerifyLoginCodeEmail-subject-450ba359 = Approve sign-in to Firefox
5882386c6d801776-fxa_avatar_menu-VerifyShortCodeEmail-headline-e2bbf688 = Confirm your email address to begin syncing your browser.
5882386c6d801776-fxa_avatar_menu-VerifyShortCodeEmail-description-e2bbf688 = Confirm your email address to begin syncing your browser.
5882386c6d801776-fxa_avatar_menu-VerifyShortCodeEmail-subject-ef1fb997 = Confirm your account

# dcdb5ae7add825d2 - purple
# Entry ID: 85
# Name: 123Done
# Created: 2025-06-25T16:28:56.433Z
# Updated: 2025-07-31T18:34:10.481Z

dcdb5ae7add825d2-purple-shared-logoAltText-bd9c68cb = 123Done logo
dcdb5ae7add825d2-purple-shared-emailLogoAltText-bd9c68cb = 123Done logo
dcdb5ae7add825d2-purple-shared-emailFromName-7878b917 = 123Done
dcdb5ae7add825d2-purple-EmailFirstPage-headline-f11ac15c = Make Space for What Matters
dcdb5ae7add825d2-purple-EmailFirstPage-description-54faaa23 = Start your clutter-free to-do list with 123Done. Sign up with your email to create a Mozilla account and get started today.
dcdb5ae7add825d2-purple-EmailFirstPage-primaryButtonText-29ff216d = Create My List
dcdb5ae7add825d2-purple-SignupSetPasswordPage-headline-45436174 = Create Your Password
dcdb5ae7add825d2-purple-SignupSetPasswordPage-description-e9b4f69a = Keep your account private and secure. Set a password for your Mozilla account and get started with 123Done.
dcdb5ae7add825d2-purple-SignupSetPasswordPage-primaryButtonText-a0bfb8e5 = Continue
dcdb5ae7add825d2-purple-SignupConfirmCodePage-headline-20f65144 = Almost There
dcdb5ae7add825d2-purple-SignupConfirmCodePage-description-09d5ff7f = Just one quick step. Enter the code from your email to activate your Mozilla account and unlock 123Done.
dcdb5ae7add825d2-purple-SignupConfirmCodePage-primaryButtonText-223d7226 = Finish Setup
dcdb5ae7add825d2-purple-SignupConfirmedSyncPage-headline-74db8403 = Sync confirmed
dcdb5ae7add825d2-purple-SignupConfirmedSyncPage-description-626b8d94 = Your account has been verified.
dcdb5ae7add825d2-purple-SignupConfirmedSyncPage-primaryButtonText-598649e6 = Add another device
dcdb5ae7add825d2-purple-SigninPage-headline-e8d28194 = Enter your password
dcdb5ae7add825d2-purple-SigninPage-description-8286e168 = for your Mozilla account
dcdb5ae7add825d2-purple-SigninPage-primaryButtonText-b6d4223e = Sign in
dcdb5ae7add825d2-purple-SigninTokenCodePage-headline-d076f12b = Enter confirmation code
dcdb5ae7add825d2-purple-SigninTokenCodePage-description-8286e168 = for your Mozilla account
dcdb5ae7add825d2-purple-SigninTokenCodePage-primaryButtonText-a0bfb8e5 = Continue
dcdb5ae7add825d2-purple-SigninUnblockCodePage-headline-72d316fb = SigninUnblockCodePage
dcdb5ae7add825d2-purple-SigninUnblockCodePage-description-4e4353da = Authorize this sign-in
dcdb5ae7add825d2-purple-SigninUnblockCodePage-primaryButtonText-a0bfb8e5 = Continue
dcdb5ae7add825d2-purple-NewDeviceLoginEmail-headline-b6494cd9 = New device login
dcdb5ae7add825d2-purple-NewDeviceLoginEmail-description-b6494cd9 = New device login
dcdb5ae7add825d2-purple-NewDeviceLoginEmail-subject-b6494cd9 = New device login
dcdb5ae7add825d2-purple-VerifyLoginCodeEmail-headline-02cf1954 = Verify login code
dcdb5ae7add825d2-purple-VerifyLoginCodeEmail-description-02cf1954 = Verify login code
dcdb5ae7add825d2-purple-VerifyLoginCodeEmail-subject-02cf1954 = Verify login code
dcdb5ae7add825d2-purple-VerifyShortCodeEmail-headline-8f70adb2 = Complete setup
dcdb5ae7add825d2-purple-VerifyShortCodeEmail-description-e1c80a1a = Confirm your account to begin using 123Done
dcdb5ae7add825d2-purple-VerifyShortCodeEmail-subject-3a7ebe9b = Confirmation code for 123Done