# Generated by Strapi webhook
# Generated at: 2025-08-01T18:30:49.546Z
# Total entries: 3
# FTL entries: 93


# 5882386c6d801776 - firefox
# Entry ID: 71
# Name: Desktop Sync222221
# Created: 2025-06-27T19:16:17.077Z
# Updated: 2025-07-25T18:21:55.773Z

0247f5588388dc32afece07727378721 = Firefox logo123
96e4284e7bf383ef08a61a787c5cec6d = Firefox logo
502f1bd97b0e7d80b88e1f45ae1bfdb8 = Mozilla
33e9f42dad0e953198693e1b8b287ac7 = Continue to your Mozilla account
4ac18cace6b4e3b50a7cfed32bf32791 = Sync your passwords, tabs, and bookmarks everywhere you use Firefox.
a20eb81efefa1f19df5622029b24713d = Sign up or sign in
72786b8adca093f30be8fd768693580a = Create a password
201c6fe143fb464058c5fde1497edcb3 = Sync your passwords, payment methods, bookmarks, and more everywhere you use Firefox.
42369faa6a6b243aac58683f3874bf99 = Create account
d076f12b21f6c04264c4951fb1440d53 = Enter confirmation code
daaed7573e31f7c4d6488fb8ae0b82ad = Just one quick step. Enter the code from your email to activate your Mozilla account.
e4029ca4594eb1cc0107b266b1ae6801 = Start syncing
3ed2d22880e1d1e3f40de26f77bc1e8a = Sync is turned on
2115ee89c7bbf60195f45f11c7634de9 = Your passwords, payment methods, addresses, bookmarks, history, and more can sync everywhere you use Firefox.
598649e62a0bb5e1636e00f42d3787d3 = Add another device
e8d28194f9b3498d21fbda21321d0226 = Enter your password
8286e168debca3a000b5664af314e493 = for your Mozilla account
b6d4223e60986fa4c9af77ee5f7149c5 = Sign in
d076f12b21f6c04264c4951fb1440d53 = Enter confirmation code
8286e168debca3a000b5664af314e493 = for your Mozilla account
e4029ca4594eb1cc0107b266b1ae6801 = Start syncing
d076f12b21f6c04264c4951fb1440d53 = Enter confirmation code
8286e168debca3a000b5664af314e493 = for your Mozilla account
a0bfb8e59e6c13fc8d990781f77694fe = Continue
f8578b7cc40aaf56358b9df06e964cb1 = Use the included code to confirm your Mozilla account.
ef1fb99744c1e164c8c787cbb6c6fd24 = Confirm your account
ef1fb99744c1e164c8c787cbb6c6fd24 = Confirm your account

# 5882386c6d801776 - fxa_avatar_menu
# Entry ID: 83
# Name: Desktop Sync - fxa_avatar_menu
# Created: 2025-06-23T20:00:42.906Z
# Updated: 2025-07-31T18:31:33.262Z

96e4284e7bf383ef08a61a787c5cec6d = Firefox logo
96e4284e7bf383ef08a61a787c5cec6d = Firefox logo
763f7f1aec350cd1a46238d1d5c3c229 = Firefox
33e9f42dad0e953198693e1b8b287ac7 = Continue to your Mozilla account
4ac18cace6b4e3b50a7cfed32bf32791 = Sync your passwords, tabs, and bookmarks everywhere you use Firefox.
e0c4332e8c13be976552a059f106354f = Get Started
7e0aff4aeb8279964bc88a5221ad1c0b = Set your password
9383a42fffc6fab7b959c06b6a60c50b = Create a strong and secure password to encrypt your data.
af214972865d03cc4eb63ed9f0b75554 = Set Password
d076f12b21f6c04264c4951fb1440d53 = Enter confirmation code
1e791281b173da64d99654693fb3fe9d = One last step, verify your account email address.
6b862186923987b6187154138271326d = Confirm Email
068241d3ee3fa98d49ba87b271742b51 = You are syncing Firefox
80ddaf0e24d0b02154a42e11e4c03140 = Your passwords, addresses, bookmarks, history, and more can sync everywhere you use Firefox...
494777176348ccba83d2d5227df67a28 = The next thing
e8d28194f9b3498d21fbda21321d0226 = Enter your password
673ee3c7e3e0607b998f21fbac3fd5da = to log into Firefox and start syncing.
b6d4223e60986fa4c9af77ee5f7149c5 = Sign in
d076f12b21f6c04264c4951fb1440d53 = Enter confirmation code
1e791281b173da64d99654693fb3fe9d = One last step, verify your account email address.
a0bfb8e59e6c13fc8d990781f77694fe = Continue
32aa265bd87d9be0d611f21098ddf2d9 = Autorize this sign in
a7ba1d71526fb6f8d756b03fc15af76d = We want to make sure it is you. Verify your email addres.
7f83df9cd29577d544efd9ff66d7118a = Authorize
a0a749e1c0bd85b36c955702e7829a61 = New sign-in to Firefox
361824c13387ad4fbafed50ddd8082fe = You have signed into Firefox
a0a749e1c0bd85b36c955702e7829a61 = New sign-in to Firefox
fe389eef5c80cc7becb06b7605a3f83b = Enter the verification code in Firefox
fe389eef5c80cc7becb06b7605a3f83b = Enter the verification code in Firefox
450ba35999dd5b05031c61dece8abe2c = Approve sign-in to Firefox
e2bbf68893fd5987334f30eee4e69b88 = Confirm your email address to begin syncing your browser.
e2bbf68893fd5987334f30eee4e69b88 = Confirm your email address to begin syncing your browser.
ef1fb99744c1e164c8c787cbb6c6fd24 = Confirm your account

# dcdb5ae7add825d2 - purple
# Entry ID: 91
# Name: 123Done
# Created: 2025-06-25T16:28:56.433Z
# Updated: 2025-08-01T18:30:48.894Z

bd9c68cb42fe5ee3f7498e42850416db = 123Done logo
bd9c68cb42fe5ee3f7498e42850416db = 123Done logo
6107fd8bf977af127ee2fbaf702c25a8 = 123Donee
f11ac15cb741a42b1f266c52766468eb = Make Space for What Matters
54faaa2344139d1f63dc526d54d7a0f2 = Start your clutter-free to-do list with 123Done. Sign up with your email to create a Mozilla account and get started today.
29ff216d41f26585c70ce3b06357e4ff = Create My List
454361743d10f2e74b9fe6c5de39ea5f = Create Your Password
e9b4f69a992f6993a254c433d348ea21 = Keep your account private and secure. Set a password for your Mozilla account and get started with 123Done.
a0bfb8e59e6c13fc8d990781f77694fe = Continue
20f6514431ee18308cbedb2095c595bb = Almost There
09d5ff7f683294b1bf0c65d2c9f06029 = Just one quick step. Enter the code from your email to activate your Mozilla account and unlock 123Done.
223d7226693427e0983c422e4b359502 = Finish Setup
74db8403865bdfb3d8ea969eeb7c32dc = Sync confirmed
626b8d941e80d815dd80a218602681f1 = Your account has been verified.
598649e62a0bb5e1636e00f42d3787d3 = Add another device
e8d28194f9b3498d21fbda21321d0226 = Enter your password
8286e168debca3a000b5664af314e493 = for your Mozilla account
b6d4223e60986fa4c9af77ee5f7149c5 = Sign in
d076f12b21f6c04264c4951fb1440d53 = Enter confirmation code
8286e168debca3a000b5664af314e493 = for your Mozilla account
a0bfb8e59e6c13fc8d990781f77694fe = Continue
72d316fbf68668aa7df8184595c42648 = SigninUnblockCodePage
4e4353daae1d42cce369ed03e66d579f = Authorize this sign-in
a0bfb8e59e6c13fc8d990781f77694fe = Continue
b6494cd9489f5ae4b9535fdb766641db = New device login
b6494cd9489f5ae4b9535fdb766641db = New device login
b6494cd9489f5ae4b9535fdb766641db = New device login
02cf19545865df33db258a7408f72a22 = Verify login code
02cf19545865df33db258a7408f72a22 = Verify login code
02cf19545865df33db258a7408f72a22 = Verify login code
8f70adb2eebdea2e00d5d57216cd59b5 = Complete setup
e1c80a1af10556e7bdc0c2fed755c342 = Confirm your account to begin using 123Done
3a7ebe9b585302fcba5d6277e3bfc839 = Confirmation code for 123Done